{
  ResultCode: 200,
  Message: [],
  Data: [
    {
      UserId: 44,
      ApiId: 20,
      UserTypeId: 0,
      NameSurname: null,
      Username: 'aykanadana',
      Password: 'QK2UUcE1x1SHrkeZPv+1Ug==',
      TSFormId: null,
      TSCampaingId: null,
      SRFormId: null,
      SRCampaingId: null,
      TAFormId: null,
      TACampaingId: null,
      CFormId: null,
      CCampaingId: null,
      IsBorusanPremium: false,
      IsActive: true,
      IsLocked: false,
      IsOurTeam: false,
      Url: 'aykanadana.audi.com.tr',
      AdminUrl: 'audiby.smartddm.com',
      Telephone: '0 322 421 5576',
      Telephone2: null,
      Telephone3: '0 322 421 5576',
      Telephone4: null,
      Telephone5: null,
      Gsm: null,
      Gsm2: null,
      Gsm3: null,
      Fax: '0 322 421 4670',
      Fax2: null,
      Fax3: null,
      GoogleMap: null,
      Logo: null,
      Email: 'audisatis@isotlar.com.tr ',
      Email2: 'audiservis@isotlar.com.tr',
      Email3: null,
      Email4: null,
      Email5: null,
      GetYouBMWUrl: null,
      CompanyName: 'AYKAN OTOMOTİV (ADANA)',
      CompanyShortName: 'AYKAN OTOMOTİV (ADANA)',
      CompanyShortNameTag: null,
      CompanySlogan: null,
      Facebook: 'https://www.facebook.com/AykanAudi/',
      Twitter: null,
      GooglePlus: null,
      Youtube: null,
      Linkedin: null,
      GoogleLatitude: '36.995732',
      GoogleLongitude: '35.272127',
      YandexLatitude: null,
      YandexLongitude: null,
      MersisNo: null,
      InformationCentralUrl: '#',
      Instagram: null,
      CityId: 0,
      DistrictId: 0,
      Address: 'Turhan Cemal Beriker Bulvarı No:416',
      Address2: null,
      WorkingTime: '  <li class="iph-opening-hours__list-item">\r\n' +
        '                        <span>H.içi: </span> <span class="m_opening_hours__item_hours">  08:15 – 18:00</span>\r\n' +
        '                    </li>\r\n' +
        '                    <li class="iph-opening-hours__list-item">\r\n' +
        '                        <span>Cmt: </span> <span class="m_opening_hours__item_hours">  08:15 – 16:30 </span>\r\n' +
        '                    </li>\r\n' +
        '                    <li class="iph-opening-hours__list-item">\r\n' +
        '                        <span>Pz: </span> <span class="m_opening_hours__item_hours">   12:00 - 16:30 </span>\r\n' +
        '                    </li>',
      WorkingTime2: '  <li class="iph-opening-hours__list-item">\r\n' +
        '                        <span>H.içi: </span> <span class="m_opening_hours__item_hours">  08:15 – 18:00</span>\r\n' +
        '                    </li>\r\n' +
        '                    <li class="iph-opening-hours__list-item">\r\n' +
        '                        <span>Cmt: </span> <span class="m_opening_hours__item_hours">  08:15 – 12:30</span>\r\n' +
        '                    </li>\r\n' +
        '                    <li class="iph-opening-hours__list-item">\r\n' +
        '                        <span>Pz: </span> <span class="m_opening_hours__item_hours"> Kapalı </span>\r\n' +
        '                    </li>',
      WorkingTime3: null,
      WorkingTime4: null,
      WorkingTime5: null,
      WorkingTime6: null,
      GoogleAnalytics: null,
      TaxNumber: null,
      UserCode: null,
      GoogleTracking: null,
      LongContent: '#',
      LongContent2: 'Aykan Motor Servis Ltd. Şti. Otomotiv sektöründe değişik markaların bayiliğini ve distribütörlüğünü yürüten İsotlar Grubunun bir kuruluşu olarak 1996 yılında kuruldu.Grup şirketlerinin toplandığı Adana-Mersin Karayolu Turhan Cemal Beriker Bulvarı üzerine inşa edilen yeni tesislerine 2006 yılı başında taşınan Aykan Audi 800 m2 alanda Satış-Servis-Yedek Parça hizmetlerini sunmaktadır.',
      LongContent3: '8',
      LastLoginDate: '/Date(1572529823123)/',
      DateCreated: '/Date(1571926425457)/',
      DateUpdated: '/Date(1625554076763)/',
      ZoneId: null,
      CommercialTitle: 'AYKAN MOTOR SERVİS A.Ş. ',
      SubDomain: null,
      SubDomain2: null,
      SubDomain3: null,
      CrmCode: null,
      Dns1: null,
      Dns2: null,
      RemoteIp: null,
      TaxOffice: null,
      ScriptHead: null,
      ScriptBody: null,
      Latitude: null,
      Longitude: null,
      GoogleProfileId: '203301809',
      IsBranch: true,
      BranchLatitude: null,
      BranchLongitude: null,
      BranchZoom: null,
      IsTest: false,
      IsAdministrator: false,
      UserType: [Object],
      City: [Object],
      District: [Object],
      IsShowroom: false
    }
  ]
}